[package]
name = "physics-testing"
version = "0.1.0"
authors = ["Khademul Mahin <mahinsemail@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
rand = "0.8"
